with SDL;
with SDL.Assert;
with SDL.Atomic;
with SDL.Audio;
with SDL.BlendMode;
with SDL.Clipboard;
with SDL.CPUinfo;
with SDL.Endian;
with SDL.Error;
with SDL.Events;
with SDL.Filesystem;
with SDL.GameController;
with SDL.Gesture;
with SDL.Haptic;
with SDL.Joystick;
with SDL.Keyboard;
with SDL.Keycode;
with SDL.LoadSO;
with SDL.Log;
with SDL.Main;
with SDL.MessageBox;
with SDL.Mouse;
with SDL.Mutex;
with SDL.Pixels;
with SDL.Platform;
with SDL.Power;
with SDL.Rect;
-- with SDL.Render;
with SDL.RWops;
with SDL.Scancode;
with SDL.Sensor;
with SDL.Shape;
with SDL.Stdinc;
with SDL.Surface;
-- with SDL.System;
with SDL.Thread;
with SDL.Timer;
with SDL.Touch;
with SDL.Version;
with SDL.Video;

package SDL_Includes is
end SDL_Includes;
